language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson libswitchboard-2.0-dev libgranite-dev libpolkit-gobject-1-dev valac libdbus-1-dev"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build --prefix=/usr && cd build && ninja"

script:
 - echo BUILDS PASSED
